# Generated by Django 3.0.3 on 2020-02-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=20, unique=True, verbose_name='Reference ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('gene', models.CharField(max_length=30, verbose_name='Gene symbol')),
                ('ec_number', models.CharField(blank=True, max_length=20, verbose_name='EC number')),
                ('flag', models.CharField(blank=True, max_length=20, verbose_name='flag')),
                ('organism', models.CharField(max_length=255, verbose_name='organism')),
                ('source_db', models.CharField(max_length=20, verbose_name='source_db')),
                ('sequence', models.TextField(verbose_name='Sequence')),
            ],
        ),
    ]
