# Generated by Django 3.0.3 on 2020-02-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='ec_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='EC number'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='flag',
            field=models.CharField(blank=True, max_length=20, verbose_name='Flag'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='gene',
            field=models.CharField(blank=True, max_length=30, verbose_name='Gene symbol'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='organism',
            field=models.CharField(max_length=255, verbose_name='Organism'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='source_db',
            field=models.CharField(max_length=20, verbose_name='Source DB'),
        ),
    ]
